# Generated by Django 3.1.7 on 2021-03-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magyk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('image', models.FileField(default='', upload_to='uploads')),
                ('background', models.FileField(default='', upload_to='uploads')),
            ],
        ),
    ]
