# Generated by Django 3.1.7 on 2021-03-30 21:01

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magyk', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
