# Generated by Django 3.1.7 on 2021-03-30 21:09

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magyk', '0003_auto_20210330_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
    ]
