# Generated by Django 3.1.7 on 2021-04-07 16:28

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magyk', '0003_auto_20210406_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='background',
        ),
        migrations.AddField(
            model_name='marketsegments',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='_type',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='platforms',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='step1',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='step2',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='step3',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='step4',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
